(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={i:!0},l={};try{l.__proto__=k;h=l.i;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=g;
function p(a,b){a.prototype=f(b.prototype);a.prototype.constructor=a;if(n)n(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var q=this||self;
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){var b=["mys","design","init"],c=q;b[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===a?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=a}function u(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};function v(){this.b=[];this.a={};this.c=!0;if(0<this.b.length){for(var a=0;a<this.b.length;a++){var b=this.b[a],c=b[0];this.a[c.toString()]=new w(c,b[1])}this.c=!0}}v.prototype.f=function(){var a;if(!this.c){this.b.length=0;var b=x(this);b.sort();for(var c=0;c<b.length;c++){var d=this.a[b[c]];(a=d.a)&&a.f();this.b.push([d.key,d.value])}this.c=!0}return this.b};function y(a){this.a=0;this.b=a}y.prototype.next=function(){return this.a<this.b.length?{done:!1,value:this.b[this.a++]}:{done:!0,value:void 0}};
"undefined"!=typeof Symbol&&(y.prototype[Symbol.iterator]=function(){return this});v.prototype.entries=function(){var a=[],b=x(this);b.sort();for(var c=0;c<b.length;c++){var d=this.a[b[c]];a.push([d.key,d.value])}return new y(a)};v.prototype.keys=function(){var a=[],b=x(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.a[b[c]].key);return new y(a)};v.prototype.values=function(){var a=[],b=x(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.a[b[c]].value);return new y(a)};
v.prototype.set=function(a,b){var c=new w(a);c.value=b;this.a[a.toString()]=c;this.c=!1;return this};v.prototype.get=function(a){if(a=this.a[a.toString()])return a.value};v.prototype.has=function(a){return a.toString()in this.a};function x(a){a=a.a;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function w(a,b){this.key=a;this.value=b;this.a=void 0};function z(){}var aa="function"==typeof Uint8Array;function A(a,b,c){a.b=null;b||(b=[]);a.l=void 0;a.g=-1;a.a=b;a:{if(b=a.a.length){--b;var d=a.a[b];if(null!==d&&"object"==typeof d&&"array"!=r(d)&&!(aa&&d instanceof Uint8Array)){a.h=b-a.g;a.c=d;break a}}a.h=Number.MAX_VALUE}a.j={};if(c)for(b=0;b<c.length;b++)if(d=c[b],d<a.h)d+=a.g,a.a[d]=a.a[d]||B;else{var e=a.h+a.g;a.a[e]||(a.c=a.a[e]={});a.c[d]=a.c[d]||B}}var B=[];
function C(a,b){if(b<a.h){b+=a.g;var c=a.a[b];return c===B?a.a[b]=[]:c}if(a.c)return c=a.c[b],c===B?a.c[b]=[]:c}function D(a){a=C(a,2);return null==a?0:a}function E(a,b){a=C(a,b);a=null==a?a:!!a;return null==a?!1:a}function F(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=C(a,c);d&&(a.b[c]=new b(d))}return a.b[c]}function G(a){if(a.b)for(var b in a.b){var c=a.b[b];if("array"==r(c))for(var d=0;d<c.length;d++)c[d]&&c[d].f();else c&&c.f()}}z.prototype.f=function(){G(this);return this.a};
function H(a){return new I(a?JSON.parse(a):null)}z.prototype.toString=function(){G(this);return this.a.toString()};function J(a){A(this,a,ba)}u(J,z);var ba=[5];function K(a){A(this,a,ca)}u(K,z);var ca=[17];function L(a){A(this,a,da)}u(L,z);var da=[27];function I(a){A(this,a,ea)}u(I,z);var ea=[8];function fa(){};function M(a,b){a=a.getElementsByTagName("META");for(var c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content");return""}function N(a,b,c){for(var d=a.getElementsByTagName("META"),e=0;e<d.length;++e)if(d[e].getAttribute("name")===b){d[e].setAttribute("content",c);return}d=document.createElement("META");d.setAttribute("name",b);d.setAttribute("content",c);a.appendChild(d)};function O(a,b){this.b=a;this.a=b;a=M(b,"namespace");a||(a="ns-"+Math.random().toString(36).substr(2,5),N(b,"namespace",a))}function P(a,b){b=new CustomEvent(b);a.a.dispatchEvent(b)};function Q(){this.a={};this.b={};this.c={}}Q.prototype.set=function(a,b){this.a[a]=b};Q.prototype.get=function(a){return this.a[a]};function R(a,b){if(b){b=JSON.parse(b);for(var c in b)a.set(c,b[c])}};function V(){this.a=new Q}p(V,fa);function W(a,b){this.b=a;this.a=b}
function ha(a){if(!mys.Engine)throw Error("MysidiaJsError[2] ");var b=a.a.b,c=a.a.a;R(a.b.a,M(c,"runtime_data"));var d=M(c,"render_config");if(!d)throw Error("MysidiaJsError[35] ");var e=H(d),m=mys.Engine.create(b,c,e.f()),S=0;c.addEventListener("browserRender",function(){++S;if(1==S)P(a.a,"overallStart"),ia(a,e),m.enable().then(function(){P(a.a,"overallQuiet")});else{var T=c.clientWidth,U=c.clientHeight;T&&U&&m.enable(T,U)}});a.b.a.get("EXP_design_dispatch_browser_render")&&P(a.a,"browserRender")}
function ia(a,b){if(!(2==D(b)||F(F(b,L,1),K,10)&&E(F(F(b,L,1),K,10),16))){var c=a.a.a;c.addEventListener("browserStart",function(){if(F(F(b,L,1),K,10)&&E(F(F(b,L,1),K,10),15)){var d=a.b.a;for(var e in d.c)d.a.hasOwnProperty(e)||d.set(e,JSON.stringify(d.c[e]));for(var m in d.b)d.a.hasOwnProperty(m)||d.set(m,JSON.stringify(d.b[m]));(d=(d=JSON.stringify(d.a))&&"{}"!=d?d:"")&&N(c,"runtime_data",d)}});c.addEventListener("browserReady",function(){});c.addEventListener("browserQuiet",function(){})}}
function ka(a,b){2==D(b)||F(F(b,L,1),K,10)&&E(F(F(b,L,1),K,10),16)||(b=0,mys.engine&&(b=mys.engine.stage()),a=a.a.a,0==(b&1)&&a.addEventListener("overallStart",function(){}),a.addEventListener("browserStart",function(){}),a.addEventListener("browserReady",function(){}),a.addEventListener("browserQuiet",function(){}))};new J;function X(){this.a=new Q;new v}p(X,V);function Y(){X.apply(this,arguments)}p(Y,X);function Z(){Y.apply(this,arguments)}p(Z,Y);(function(a){var b=document.getElementById("mys-content");if(b){b=new O(document.head,b);var c=a(b);c=new W(c,b);R(c.b.a,M(b.a,"runtime_data"));if("true"===c.b.a.get("EXP_async_load_design")){b=H(M(b.a,"render_config")||"[]");ka(c,b);return}}t(function(d,e){d=new O(d,e);e=a(d);ha(new W(e,d))})})(function(a){return new Z(a)});}).call(this);
